---
title: Oxytocin and Vasopressin Receptors in the Pouched Rat
author:
  - name: Samanta Arenas
    email: sa658@cornell.edu
    affiliation: Cornell University
  - name: Angela R. Freeman
    email: arf86@cornell.edu
    affiliation: Cornell University
  - name: Bhupinder Singh
    email: bs256@cornell.edu
    affiliation: Vetschool
  - name: Alexander G. Ophir
    email: ophir@cornell.edu
    affiliation: Cornell University
    footnote: 1
address:
  - code: Cornell University
    address: Cornell University, Department of Psychology, Ithaca, NY, 14853
  - code: Vetschool
    address: Cornell University, Department of Veterinary Medicine, Ithaca, NY, 14853

footnote:
  - code: 1
    text: "Corresponding Author"

abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "Journal of Neuroscience"
date: "`r Sys.Date()`"
bibliography: library.bib
linenumbers: true
#numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
---

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_

```{r}
x <- c(1,6,8,12,10)
y <- c(4,5,6,7,8)

plot(x,y)
```

The Elsevier article class
==========================

#### Installation

If the document class *elsarticle* is not available on your computer,
you can download and install the system package *texlive-publishers*
(Linux) or install the LaTeX package *elsarticle* using the package
manager of your TeX installation, which is typically TeX Live or MikTeX.

#### Usage

Once the package is properly installed, you can use the document class
*elsarticle* to create a manuscript. Please make sure that your
manuscript follows the guidelines in the Guide for Authors of the
relevant journal.[@davisAlarmCallingRichardson1984; @hareJuvenileRichardsonGround1998] It is not necessary to typeset your manuscript in
exactly the same way as an article, unless you are submitting to a
camera-ready copy (CRC) journal.

#### Functionality

The Elsevier article class is based on the standard article class and
supports almost all of the functionality of that class. In addition, it
features commands and options to format the

-   document style

-   baselineskip

-   front matter

-   keywords and MSC codes

-   theorems, definitions and proofs

-   lables of enumerations

-   citation style and labeling.

Front matter
============

The author names and affiliations could be formatted in two ways:

(1) Group the authors per affiliation.

(2) Use footnotes to indicate the affiliations.

See the front matter of this document for examples. You are recommended
to conform your choice to the journal you are submitting to.

Bibliography styles
===================

There are various bibliography styles available [@Austad1985]. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
